### ISSUE TITLE
[Question] Is there a way to test sideeffects of a method

### ISSUE THREAD

**Issue by danielepo** [github/Scientist.net#89]
As an example I have a method that:

- Receives some Input
- Prepares the data, for example bulids a query
- calls a dependecy, for example execute a query

the call could be considered an indirect output. Is there a way to intercept the indirect output to ensure that a refactored version of the method still does the same call?

**Comment by joncloud** [comment]
Right now Scientist requires some kind of output in order to do comparisons.  If the query has some kind of output, then Scientist could be used to compare the results.  For example the query could return an object representation of a `SELECT`, or it could inspect the total number of rows modified from an `UPDATE`.

I can provide some more guidance with some more concrete examples.
